spring:
  application:
    name: JobBuilder
server:
  port: 8082

flink:
  job-manager:
    host: localhost
    port: 8081
  job-jar-path: target/flink-request-counter-1.0.0-flink-job.jar
  redis-host-in-cluster: redis
  redis-port-in-cluster: 6379